### ISSUE TITLE
字段类型不对应

### ISSUE THREAD

**Issue by buptzyf** [insistence/RuoYi-Vue3-FastAPI#5]
ruoyi-fastapi.sql中user.status和del_flag都是字符类型，但是代码中查询的时候比较的是用integer和char作比较，所以代码跑不通

 role_info = (await db.execute(
            select(SysRole)
                .where(SysRole.role_id != 1, SysRole.status == 0, SysRole.del_flag == 0)
        )).scalars().all()

**Comment by buptzyf** [comment]
sqlalchemy.exc.ProgrammingError: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedFunctionError'>: 操作符不存在: character = integer
HINT:  没有匹配指定名称和参数类型的操作符. 您也许需要增加明确的类型转换.
[SQL: SELECT sys_role.role_id, sys_role.role_name, sys_role.role_key, sys_role.role_sort, sys_role.data_scope, sys_role.menu_check_strictly, sys_role.status, sys_role.del_flag, sys_role.create_by, sys_role.create_time, sys_role.update_by, sys_role.update_time, sys_role.remark 
FROM sys_role 
WHERE sys_role.role_id != $1::INTEGER AND sys_role.status = $2::INTEGER AND sys_role.del_flag = $3::INTEGER]
[parameters: (1, 0, 0)]

**Comment by insistence** [comment]
在MySQL中这不影响，会自动转换，看你的报错信息你是使用了postgresql吧

**Comment by buptzyf** [comment]
> 在MySQL中这不影响，会自动转换，看你的报错信息你是使用了postgresql吧

感谢周末的及时回复，我切换成postgresql了，对postgresql不太熟，它在查询时没有类型的自动转换
Column定义时的String类型改为
class IntegerToString(TypeDecorator):

    impl = String

    def process_bind_param(self, value, dialect):
        if isinstance(value, int):
            return str(value)
        return value

    def process_result_value(self, value, dialect):
        if value is not None:
            return str(value)
        return value
可以成功获取token了，谢谢

**Comment by insistence** [comment]
从严谨角度来说，我会在后面的版本修改这个，感谢反馈
