### ISSUE TITLE
切换pg数据库service和dao层不兼容

### ISSUE THREAD

**Issue by libeng** [insistence/RuoYi-Vue3-FastAPI#7]
除了SysOperLog表中status是Integer, 其余表中的status都是String(1)类型, 但是在很多查询构建都是令 table.status==0 , 应该改为 table.status=="0"

**Comment by insistence** [comment]
和#5一样的问题，前几天已经在develop分支优化过了，近期会发布新的版本

**Comment by insistence** [comment]
1.3.0版本已修改

**Comment by insistence** [comment]
1.5.0版本已支持pg数据库
